name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  test-results:
    description: 'Path to the directory containing trx files'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
