name: 'Report Test Results'
description: 'A GitHub action to parse test results and post the summary as a PR comment'
inputs:
  test-results:
    description: 'Path to the directory containing trx files'
    required: true
  github-token:
    description: 'GitHub repository token'
    required: false
  comment-title:
    description: 'Pull Request comment title'
    required: false
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
