name: 'Dotnet Test Reporter'
description: 'A GitHub action to parse test results and post the summary as a PR comment'
author: 'https://github.com/bibipkins'
branding:
  icon: 'check-square'
  color: 'white'
inputs:
  github-token:
    description: 'GitHub repository token'
    required: true
  test-results:
    description: 'Path to the directory containing trx files'
    required: true
  test-coverage:
    description: 'Path to the file containing test coverage'
    required: false
  min-coverage:
    description: 'Minimum allowed coverage (from 0.00 to 100.00)'
    required: false
  comment-title:
    description: 'Pull Request comment title'
    required: false
  post-new-comment:
    description: 'Boolean flag. Set to true to post a new comment after each run'
    required: false
    default: false
outputs:
  tests-total:
    description: 'Total number of tests'
  tests-passed:
    description: 'Number of tests passed'
  tests-failed:
    description: 'Number of tests failed'
  tests-skipped:
    description: 'Number of tests skipped'
  coverage-line:
    description: 'Line code coverage'
  coverage-branch:
    description: 'Branch code coverage'
runs:
  using: 'node16'
  main: 'dist/index.js'
