name: build

on:
  push:
    branches:
      - main
      - feature/**
      - fix/**
      - bugfix/**
      - hotfix/**
  pull_request:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test step
        uses: ./
        id: hello
        with:
          test-results: './'
