name: Build and Test

on:
  push:
    branches:
      - main
      - feature/**
      - fix/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
      - run: |
          npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test OpenCover
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: Test OpenCover
          results-path: ./files/
          coverage-path: ./files/test_coverage_opencover.xml
          coverage-threshold: 46
      - name: Test Cobertura
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: Test Cobertura
          results-path: ./files/
          coverage-path: ./files/test_coverage_cobertura.xml
          coverage-type: cobertura
          coverage-threshold: 46
