name: test

on:
  push:
    branches:
      - main
      - feature/**
      - fix/**
      - bugfix/**
      - hotfix/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
      - run: |
          npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action_test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-results: ./test-files/
          test-coverage: ./test-files/coverage.xml
          min-coverage: 50.71
